services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  user-service:
    build:
      context: ./backend/user-service

    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user-service
    depends_on:
      - mongodb
      - notification-service
    networks:
      - app-network

  task-service:
    build:
      context: ./backend/task-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/task-service
    depends_on:
      - mongodb
      - notification-service
      - user-service
    networks:
      - app-network

  notification-service:
    build:
      context: ./backend/notification-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notification-service
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5050:80"
    depends_on:
      - user-service
      - task-service
      - notification-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
