version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./backend/user-service
    container_name: user-service
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  task-service:
    build: ./backend/task-service
    container_name: task-service
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    ports:
      - "3002:3002"

  frontend:
    image: node:18-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npx","http-server","-p","8080"]
    ports:
      - "8080:8080"
